<?php

/**
 * Created by PhpStorm.
 * User: MarOleVik
 * Date: 19.06.2018
 * Time: 18:21
 */
return [
    /*COMMON*/
    'enable' => 'Увімкнено',
    'disable' => 'Вимкнено',
    'all' => 'Усе',
    'show' => 'ПоказатИ',
    'entries' => 'елементів',
    'image' => 'Зображення',
    'items_on_the_page' => 'Елементів на сторінці',
    'pagination_results' => 'Показано з %s по %s із %s (всього %s %s)',
    'pages' => 'сторінка|сторінки|сторінок',
    /*TITLES*/
    'title_dashboard' => 'Панель Управління',
    'title_content' => 'Контент',
    'title_manufacturer' => 'Виробник',
    'title_manufacturers' => 'Виробники',
    'title_informations' => 'Статті',
    'title_shipping_methods' => 'Методи доставки',
    'title_attribute_group' => 'Групи атрибутів',
    'title_status' => 'Статус',
    'title_sort_order' => 'Сортування',
    'title_actions' => 'Дії',
    'title_language' => 'Мови',
    'title_category' => 'Категорії',
    'title_category_parent' => 'Батьківська категорія',
    'title_image' => 'Зображення',
    /*MENU*/
    'menu_manufacturers' => 'Виробники',
    'menu_shipping_methods' => 'Методи доставки',
    'menu_news' => 'Новини',
    'menu_authors' => 'Автори до статей',
    'menu_informations' => 'Статті',
    'menu_cache' => 'Очищення кешу',
    'menu_attributes' => 'Атрибути',
    'menu_attribute_words' => 'Слова для атрибутів',
    'menu_attributes_group' => 'Групи атрибутів',
    'menu_banners' => 'Банери',
    'menu_combinations' => 'Питання-відповідь',
    'menu_combinations_generate' => 'Підбір товарів',
    'menu_combinations_questions' => 'Список питань',
    'menu_combinations_answers' => 'Список відповідей',
    'menu_banner_list' => 'Список банерів',
    'menu_banner_groups' => 'Групи банерів',
    'menu_filters' => 'Фільтра',
    'menu_filters_group' => 'Групи фільтрів',
    'menu_settings' => 'Налаштування',
    'menu_individual_entrepreneurs' => 'ФОПи',
    'menu_languages' => 'Мови',
    'menu_options' => 'Опції',
    'menu_options_value_group' => 'Групи значень опцій',
    'menu_option_value' => 'Значення опцій',
    'menu_categories' => 'Категорії',
    'menu_seodata' => 'Seo data',
    'menu_seodata_url' => 'Url Seo data',
    'menu_products' => 'Товари',
    'menu_kit' => 'Комплекти',
    'menu_filling' => 'Наповнення',
    'menu_panoramas' => 'Квартири',
    'menu_services' => 'Сервіси',
    'menu_message' => 'Повідомлення',
    'menu_reviews' => 'Відгуки',
    'menu_bad_reviews' => 'Товари з поганими відгуками',
    'menu_stock_statuses' => 'Статуси',
    'menu_currencies' => 'Валюти',
    'menu_regions' => 'Регіони',
    'menu_locations' => 'Локації',
    'menu_segments' => 'Сегменти',
    'menu_sales' => 'Акції',
    'menu_sale_groups' => 'Групи акцій',
    'menu_tree_discount' => 'Дерево знижок',
    'menu_cashback' => 'Кешбек',
    'menu_discounts_settings' => 'Налаштування знижок',
    'menu_bonus_programs' => 'Бонусні програми',
    'menu_promo_codes' => 'Промокоди',
    'menu_promo_code_groups' => 'Групи промокодів',
    'menu_vacancies' => 'Вакансії',
    'menu_shops' => 'Магазини',
    'menu_selling' => 'Продажі',
    'menu_orders' => 'Замовлення',
    'menu_newsletter' => 'Розсилка',
    'menu_receipts' => 'Квитанції',
    'menu_fiscalization'=>'Фіск LiqPay',
    'menu_notifications' => 'Сповіщення',
    'menu_layouts' => 'Схеми',
    'menu_modules' => 'Модулі',
    'menu_extensions' => 'Розширення',
    'menu_pages' => 'Сторінки',
    'menu_packagist' => 'Комплектації',
    'menu_attribute_icons' => 'Мініатюри атрибутів',
    /*FORMS*/
    'title_edit_form' => 'Форма редактування',
    /*INPUTS*/
    'hide_option' => 'Статус опції:',
    'comment' => 'Коментар',
    'input_custom_size' => 'Нестандартний розмір',
    'input_manufacturer' => 'Виробник',
    'input_informations' => 'Статі',
    'input_status' => 'Статус',
    'input_mark' => 'Мітка',
    'input_seo_url' => 'Seo-url',
    'input_code' => 'Код',
    'input_default' => 'По-замовчуванню',
    'input_group_attribute' => 'Група атрибутів',
    'input_group_filter' => 'Група фільтрів',
    'input_group_option' => 'Група опцій',
    'search_name' => 'Пошук по назві',
    'search_path' => 'Пошук по URL',
    'search_id' => 'Пошук по ID Замовлення',
    'button_save' => 'Зберегти',
    'button_update' => 'Оновити',
    'button_exit_update' => 'Зберегти і вийти',
    'button_add' => 'Додати',
    'button_exit_add' => 'Додати і вийти',
    'button_reset' => 'Скинути',
    'tooltip_input_seo_url' => 'SEO-URL',
    'tooltip_meta_h1' => 'Тег H1',
    'tooltip_meta_title' => 'Meta title',
    'tooltip_meta_description' => 'Meta description',
    'tooltip_meta_keywords' => 'Meta keywords',
    'last_update' => 'Актуально на ',
    'autorized' => 'Користувач',
    'button_exit' => 'Вийти',
    'error_pass' => 'Error pass',
    'error_login' => 'Error login',

    /*FORMS*/
    'filter' => 'Застосувати',
    'reset_filter' => 'Скинути',
    'choose_image' => 'Вибрати зображення',
    'choose_icon' => 'Вибрати іконку',
    'go_back' => 'Назад',
    'yes' => 'Так',
    'no' => 'Ні',
    'on' => 'Вкл',
    'off' => 'Откл',
    'do_on' => 'Увімкнути',
    'do_off' => 'Вимкнути',
    'required_field' => 'Заповніть це поле',

    /*API*/
    'all_checked' => 'Виділити все',
    'add_selected' => 'Додати виділене',
    'no_product_to_filter' => 'Товарів по цій фільтрації немає',

    /* success actions */
    'successful_delete' => 'Вдале видалення',
    'successful_update' => 'Вдале оновлення',
    'successful_insert' => 'Вдале додавання',
    'success_all' => 'Застосувати до усіх',
    'success_checked' => 'Застосувати до вибраних',

    /* error actions */
    'error_update' => 'Помилка оновлення',
    'error_insert' => 'Помилка додавання. ',
    'error_delete' => 'Помилка під час видалення',
];